application: roadtracking-pro
version: 1
runtime: java
threadsafe: true

inbound_services:
  - warmup

system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties

handlers:
  - url: /*
    filter: com.google.inject.servlet.GuiceFilter

listeners:
   - com.roadtracking.web.guice.GuiceServletConfig

welcome_files:
  - index.html